version: '3.8'

services:
  app:
    image: kolosiv/newsaggr:latest
    container_name: my_go_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: 29082002
      POSTGRES_DB: news-aggr
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
